### ISSUE TITLE
Cura Plugin

### ISSUE THREAD

**Issue by abejfehr** [ChristophSchranz/Tweaker-3#23] opened 2022-05-24 00:43 UTC
I was looking for the "Auto Orientation" plugin in [Cura's Plugin Marketplace](https://marketplace.ultimaker.com/app/cura/plugins) but I don't see it anywhere. 

I realize it says it's in the Cura Marketplace for Cura versions >=4 in the README.md, but that file was last modified before Cura 5 came out. Does it perhaps not support Cura 5?

**Comment by ChristophSchranz** [comment] 2022-05-24 07:57
Hi @abejfehr 
This is a duplicate of https://github.com/nallath/CuraOrientationPlugin/issues/20#issuecomment-1134338645
It seems it will be fixed soon!

**Closed by ChristophSchranz** 2022-05-24 07:57 UTC
